forcing:

    resolution: 200
    phase_shift: 0.2
    add_noise: True

chaotic:

  initial_conditions:
      species1_mean: 1.1
      species2_mean: 1.1
      species1_std: 0.1
      species2_std: 0.1

  observation_params: [1.18, 1, -0.03, 0.31, 0.25, 1.16, 1, -0.13, 0.52, 0.32]
  initial_params: [1.05, 1.0, 0.39, 0.44]

  observation_noise:
    stochastic: 0.05
    deterministic: 0.05
  initial_noise:
    stochastic: 0.05
    deterministic:

nonchaotic:

  initial_conditions:
      species1: 1.1
      species2: 1.1

  observation_params: [0.18, 1, -0.1, 0.41, 0.25, 0.16, 1, 0.3, 0.32, 0.32]
  initial_params: [0.087132, 0.865437, 0.34348, 0.315365]

  observation_noise:
    stochastic: 0.05
    deterministic: 0.05
  initial_noise:
    stochastic: 0.05
    deterministic:
