simulation:
    climatology : 20
    ensemble_size : 50
    resampling_size: 40

forcing:

    resolution: 200
    phase_shift: 0.0
    add_noise: False

chaotic:

  initial_conditions:
      species1_mean: 1.0
      species2_mean: 1.0
      species1_std: 0.1
      species2_std: 0.1

  observation_params:

    alpha1: 1.29
    beta1: 1
    gamma1: -0.12
    bx1: 0.41
    cx1: 0.31
    alpha2: 1.15
    beta2: 1
    gamma2: -0.13
    bx2: 0.32
    cx2: 0.42

  initial_params: [1.05, 1.0, 0.39, 0.44]

  observation_noise:
    stochastic: 0.05
    deterministic: 0.05

  initial_noise:
    stochastic: 0.05
    deterministic:

path_to_plots: "ricker/plots"
