targets_eval:
  - stl1
  - stl2
  - stl3
  #- swvl1
  #- swvl2
  #- swvl3

targets_prog:
  - swvl1
  - swvl2
  - swvl3
  - stl1
  - stl2
  - stl3
  - snowc


path_to_plots:  '../plots/'
path_to_results: '../results/'

network: 'soil_TERENO_ISMN_2022.nc' # #'soil_SMOSMANIA_ISMN_2022.nc' # 'soil_TERENO_ISMN_2022.nc'
station: 'Gevenich'  #'Condom' ## 'Lahas' # CabrieresdAvignon, 'Narbonne' 'CreondArmagnac', 'LaGrandCombe', 'LezignanCorbieres', 'Mazan-Abbaye', 'Mejannes-le-Clap'...
variable: 'st'
depth: [0.05, 0.2, 0.5]

years: [2021, 2022]
models: ['mlp', 'lstm', "xgb"] # , 'xgb'

initial_time: '2022-02-01T00:00:00'
maximum_leadtime: 1330 # long-range 

ensemble_size: 50

score: "MAE"
tolerance: 3 # Kelvin, for soil temperature. 0.1 in % for SM
